
["Female Plastic Surgery Config"]
	#Range: 0.8 ~ 4.0
	bustSizeMax = 4.0
	#Range: -4.0 ~ -1.0
	"Breast Height Min" = -4.0
	#Range: -4.0 ~ -1.0
	"Breast Depth Min" = -4.0
	#Range: 0.0 ~ 4.0
	"Breast Depth Max" = 4.0
	#Range: 0.5 ~ 3.0
	"Bounce Multiplier Max" = 3.0
	#Range: 1.0 ~ 3.0
	"Floppy Multiplier Max" = 3.0

